wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.13
    cli_version: 0.17.7
    framework: huggingface
    huggingface_version: 4.39.1
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1728043575
    t:
      1:
      - 1
      - 9
      - 11
      - 12
      - 41
      - 49
      - 55
      - 103
      2:
      - 1
      - 9
      - 11
      - 12
      - 41
      - 49
      - 55
      - 103
      3:
      - 7
      - 13
      - 23
      - 66
      4: 3.8.13
      5: 0.17.7
      6: 4.39.1
      8:
      - 2
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
data_dir:
  desc: null
  value: /home/dengruijun/data/FinTech/DATASET/image-dataset/cifar10/
test_phase:
  desc: null
  value: 0
dev:
  desc: null
  value: 0
logger:
  desc: null
  value: wandb
classifier:
  desc: null
  value: resnet34
pretrained:
  desc: null
  value: 0
precision:
  desc: null
  value: 32
batch_size:
  desc: null
  value: 128
max_epochs:
  desc: null
  value: 20
num_workers:
  desc: null
  value: 0
learning_rate:
  desc: null
  value: 0.01
weight_decay:
  desc: null
  value: 0.01
dataset:
  desc: null
  value: CIFAR10
