data_dir: /home/dengruijun/data/FinTech/DATASET/image-dataset/cifar10/
download_weights: 0
test_phase: 0
dev: 0
logger: tensorboard
classifier: resnet18
pretrained: 0
precision: 32
batch_size: 256
max_epochs: 1
num_workers: 8
gpu_id: '3'
learning_rate: 0.01
weight_decay: 0.01
